remote_theme: liminalproperty/dinky
title: Liminal Property Limited
show_downloads: false
legalfooter: Liminal Property Limited is registered in England & Wales<br/>Registration number 13333652<br/>Registered address Flat 3, 16 The Ridgeway, Enfield, EN2 8QH
