theme: jekyll-theme-dinky
title: Liminal Property Limited
show_downloads: false
description: |
  A company registered in England & Wales
  
  Company number: 13333652
  
  Registered address: Flat 3, 16 The Ridgeway, EN2 8QH
